################################
# API Manager
autodiscoveryId: "20835977"

# Listener
https:
  port: "443"
################################

db:
  host: "aws-1-eu-west-1.pooler.supabase.com"
  port: "6543"
  database: "postgres"
  user: "postgres.ooaysxcffzxichrbvfzz"